// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerformanceManagementSystem.Data;

#nullable disable

namespace PerformanceManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250429092433_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PerformanceManagementSystem.PerformanceManagementSystem.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "HR",
                            FullName = "Alice Johnson"
                        },
                        new
                        {
                            Id = 2,
                            Department = "IT",
                            FullName = "Bob Smith"
                        });
                });

            modelBuilder.Entity("PerformanceManagementSystem.PerformanceManagementSystem.Models.PerformanceGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("GoalTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Refine onboarding process for new hires.",
                            DueDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            GoalTitle = "Improve Onboarding",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Replace old servers with cloud instances.",
                            DueDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            GoalTitle = "Upgrade Infrastructure",
                            Status = 1
                        });
                });

            modelBuilder.Entity("PerformanceManagementSystem.PerformanceManagementSystem.Models.PerformanceGoal", b =>
                {
                    b.HasOne("PerformanceManagementSystem.PerformanceManagementSystem.Models.Employee", "Employee")
                        .WithMany("PerformanceGoals")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PerformanceManagementSystem.PerformanceManagementSystem.Models.Employee", b =>
                {
                    b.Navigation("PerformanceGoals");
                });
#pragma warning restore 612, 618
        }
    }
}
